# fly.toml app configuration file generated for part03-cinder-willow-8213 on 2026-07-19T02:09:32+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'part03-cinder-willow-8213'
primary_region = 'cdg'

[env]
  PORT = "3001"

[build]
[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
