
GET http://localhost:3001/api/persons

### 
GET http://localhost:3001/info

### 
GET http://localhost:3001/api/persons/6a5e3d9cda04e58f32b10924

###
DELETE http://localhost:3001/api/persons/3

###
PUT http://localhost:3001/api/persons/6a5e3d9cda04e58f32b10924
Content-Type: application/json

{
    "name": "Khalid",
    "number": "495-8499-34598"
}